# -*- coding: utf-8 -*-
"""Motis_BF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDkHajhhuTVQDP08G4MqfVoXDLryCafz
"""

from itertools import combinations_with_replacement, combinations, permutations
import os.path






def generateList(listWord):
    listOut = []
    listTemp = []
    for i in range(len(listWord)):
        for j in range(len(listWord[i])):
            for k in range(len(listWord[i][j])):
                listTemp.append(listWord[i][j][k].lower())
        listOut.append(listTemp.copy())
        listTemp.clear()
    print('0 - list generated')
    return listOut



def newList():
    listCl = []
    for i in range(0,27):
        listCl.append(0)
    return listCl



def identOccur(regsList):

    regsOccurrences = []
    regsValues = []
    listOccFinal = []

    for i in range(97,124):
        regsValues.append(i)
        regsOccurrences.append(0)


    for i in range(len(regsList)):
        listOcc = newList()

        for j in range(len(regsList[i])):
            local= ord(regsList[i][j])
            for k in range(len(regsValues)):
                if regsValues[k]==local:
                    listOcc[k] = 1
        listOccFinal.append(listOcc.copy())

    print('1 - occurrences identified')
    return listOccFinal


def countOccur(listOccur):


    listCount = newList()


    for i in range(len(listOccur)):
        lines = len(listOccur)
        for j in range(len(listOccur[i])):
            cols = j


        for k in range(cols):

            countOcc = 0
            for l in range(len(listOccur)):

                if listOccur[l][k] == 1:
                    countOcc = countOcc+1
            if countOcc==lines:
                listCount[k] =1

    print('2 - occurrences counted')



    return listCount



def strRepList(listCount):
    listOutStr = []

    for i in range(len(listCount)):
        if listCount[i] == 1:
            listOutStr.append(chr(i+97))

    print('3 - list repetitive residues generated')
    return listOutStr



def genCombnations(listIn):

  name_of_file = 'motifsGenerated'
  save_path = os.getcwd() + '/'

  completeName = os.path.join(save_path, name_of_file + ".txt")
  file = open(completeName, "w")




  for n in range(len(listIn) + 1):
      file.write(str(list(permutations(listIn, n))))

  file.close()

  print('4 - motifs generated')




listTest01 = [["MAKNITVPYVSVSDFDWGLNLEASASLPWNPTIWSLVAALTALPLWMTLELTVSVLYVFQRWSGLYFYAVLITAWSISLHAIGFLLSYCVPSCNWIASSIMTELGWVGMVTGFSLVLYSRLNLMSFIMRNRHISRIALAMIITNAVLFHIPTFVVFMIGVSSPGLFVKYISAMNALERVQIVMFSVQELILSGLYIYGTFKMAQDSFNSRIRRTI"],


["MATNITVPYVAIGDFDWGLNLASSVPLPWNQTIWSLVAVFTALPLWMTLELTVSVLYVFRRWSGLYFWAVLVTTWSISLHAIGFLLSYCVPSCNWIASSLITEFGWAGMVTGFSLVLYSRLTLLSFVMRNRHISRIALGMITTDAILFHIPTFVVFMVGISSPANFVKYVPYMNIVERIQIVMFSVQELILSGLYIYGTFKMAQDSFNSRIRRTI"],


["MADLPKLRSLVAAFTALPLWMTIELTVSVLYVFRRWSGLYFWSVLVTTWSISVHAIGFLLSYCVPSCNQIASSVLAEVGWVGMVSGFAVVLYSRLNLISFVMQNRHILRLALGMIITDAMLFHIPALVIFIIGTSSGAMFEKYVTCMNILERIQIVAFSVQELIISGLYIYGTFKMERDSFNSRIRKTIRLLITVQIAVILCDALLITLDFAGYY"],



["MAENITVPYVPFDQFHWSISYTGPLPWNQTVWSLIAVFTALPLWMTVELTVWVFYLFRRWSGLYFWSVLITTWGVTLHAIGFVLKVCVPRCNYILSMVIAELGWIGMVTGFAMVMYSRLNLIGFVMRNRYILRLALAMIIVDGIVFHTSTITIFAIGLANPSARYLSYMNAIERVQIVIFTVQEIILSVIYIYGTFKMAQDSFNNRIRSTINYLI"],


["MAGNITVPYVPFDQFHWSMSHVGPLPWNQTVWSLIAVFTALPLWITIELTICVFYLFRRWSGLYFWSVLITTWGVTLHAIGFVLKVCVPSCNYIFSMVVAELGWMGMVTGFAMVMYSRLSLIGFVMRNRYILRLALAMIIINAIVLHTSTITIFAIGIEEPGPKYLSYMNSIERIQIVIFTVQEVILSTIYIYGTFKMAQDSFNKRIRATISYLI"],

["MTSVRNITVPYVPLDEFDWSFYRSGPLPWNQTIWSLIAVFTAVPLWMTIELTVWVFYIFNRYSGLYFWSVLITTWGVTLHAIGFVLKDCVPQCSWIFSTILAEIGWVGMVTGFSVVLYSRLHLVSFVMHSSSILRLALSMIIIDALLFHVPTIVFQFGCSDPHTHAKYVAYMGPMERVQVLGFSIQETILSALYIYGTVQMFKESITSKIRTTLK"],


["MSGLHNITVPYVSTSQFDWSFARTYPLPWNQTIWSIVAVFSAVPLWMNIELTVWVLYVFRRYSGLYFWSILITTWCIALHAIGYVLKECVPDCNWILSTLIVEIGWVGMVTGFSMVLYSRLHLVNFTIKNPHILRITLIMIITDAFLFHTPTIVFQFGLANQSRHDQYASYLHVMERIQIMGFSLQEITLTSIYIYGTLQIIKSSLNSKIRTTMV"],


["MTKVHNITVPYVTVSDFDWSFARTGPLPWNQTVWSLIAVFTALPLWTTIELTVCVFYTFRRYSGLYFWSVLCTTWGVTIHAIGFVLKFCVPSCNWIFSTVLAEIGWVGMVSGFSIVLYSRLHLVVRSQRTLQLVLAAIVVDAFLFHVPTIVFQFGTSDKHTHKKFLPYMNVMERVQIVGFSVQEIIISAIYIYATMQMLRGSFNRRMRTTMAWLI"],


["MSVHNITVPYVNVIDFDWGFNRTGPLPWNQTVWSILAVFTAVPLWMTVELTIWVFYVFRRWSGLYFWSVLICTWGVTLHTIGFILKFCVPSCNWIVSTTLAEIGWVSMVTGFSVVLYSRLHLVVRSPRILNLVLIMVMTDAFLFHVPTIVFQYGISANGKTHVYYLPFMAPMERIQVFGFSIQEVVISIIYIWATLRMLKGSFNKKIRNTIIFLI"],



["MAEECVHFVKFSDYDWTFDRVGWLPWNPAAFCLIAAVCAIAYWMSIEVLVLVYVTFKRHAGIYFWSIIFTTIGIILQNTGYILLSFENTWPVILVVVICKIGWIMNVTGFSIVLWSRLHLVVRSQRILKWLLVIILIDGLVCHTPIAVFEFGLMTRNHNTYYRPMQIMERIQQTVFTIQETIMSCLYIYHTRKFLKIGYPMQTRKVVGLLLLVQL"]]

listTest = [['acztpfs'],['dicyatb'],['mactasc']]


lst = generateList(listTest01)
lstOcc = identOccur(lst)
lstCountOc = countOccur(lstOcc)
lstStr = strRepList(lstCountOc)
genCombnations(lstStr)


print('End!!!!!!!!!!!')

